name: CI Pipeline

on:
  push:
    branches: [ "main" ] # Запуск при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest # Используем ОС Ubuntu

    steps:
      # Шаг 1: Скачивание кода репозитория на виртуалку
      - name: Checkout repository code
        uses: actions/checkout@v4

      # Шаг 2: Имитация сборки / тестирования (базовый вывод в консоль)
      - name: Run a one-line script
        run: echo "Repository successfully cloned and verified!"
